// src\Typings\WebNavigation.d.ts:L128
// Please only add new members to the end of this enum (some files reference the numerical values directly).
export const enum PowerBIArtifactType {
    Unknown = 0,
    Dashboard = 1,
    Report = 2,
    Model = 3,
    Workbook = 4,
    App = 5,
    RdlReport = 6,
    Workspace = 7,
    CdsaModel = 8,
    StreamingCdsaModel = 9, // Note, this is only used in specific cases. A streaming CdsaModel is just a CdsaModel with Streaming Capabillities and most times will continue to use the CdsaModel enum.
    Scorecard = 10,
    Datamart = 11,
    Tile = 12, // Note, this is only used in specific cases. A tile is not a navigated artifact.
    StreamingModel = 13,
    DataflowGen2 = 103,
    LakeWarehouse = 14,
    DataWarehouse = 15,
}

//trident\libs\data-access\artifact\src\lib\models\artifact.ts
type TridentArtifactType =
    // PowerBiArtifactType
    | 'dashboard'
    | 'dataflow'
    | 'dataflow-gen2'
    | 'datamart'
    | 'dataset'
    | 'dataset-autogenerated'
    | 'data-warehouse'
    | 'lake-warehouse'
    | 'rdlreport'
    | 'report'
    | 'scorecard'
    | 'streaming-dataflow'
    | 'streaming-model'
    | 'workbook'
    // SimulatedArtifactType
    | 'app'
    | 'workspace'
    | 'alm-pipeline'
    | 'tile'
    | 'unknown'
    // TridentArtifactType
    | 'DigitalOperationsAction'
    | 'DigitalOperationsOperationalInsight'
    | 'Environment'
    | 'EventStream'
    | 'ExternalFunctions'
    | 'HomeOne'
    | 'KustoDashboard'
    | 'KustoDatabase'
    | 'KustoEventHubDataConnection'
    | 'KustoQueryWorkbench'
    | 'Lakehouse'
    | 'LinkedService'
    | 'MLExperiment'
    | 'MLModel'
    | 'Pipeline'
    | 'ReflexProject'
    | 'SparkJobDefinition'
    | 'SqlDatabase'
    | 'SynapseNotebook'
    | 'TestArtifact';

// src\Modern\Shared\FluentList\utils\artifact-utils.ts
export type FluentListArtifactType = PowerBIArtifactType | TridentArtifactType;

// src\Modern\Apps\Web\TridentArtifactFilter\contracts\artifact-list.ts
export const enum ArtifactListFilterGroupId {
    Type = 'type',
    Workload = 'workload',
    Time = 'time',
    Owner = 'owner',
    Endorsement = 'endorsement',
}
